### ISSUE TITLE
Create an html Form with a Textbox Input and Photo input

### ISSUE THREAD

**Issue by Tejas-Dalvi-99** [Tejas-Dalvi-99/Help-Me#1]
( Upload your code in the Contributers Codes folder )

**Comment by akhil-aggarwal** [comment]
Do we need just a simple form or need some CSS formatting also?

**Comment by akhil-aggarwal** [comment]
Please check the Pull Request sent for the Emergency Form.

**Comment by Tejas-Dalvi-99** [comment]
Yup merged that, thanks for the contribution. Great work
