### ISSUE TITLE
Emergency form response needs to be stored in database

### ISSUE THREAD

**Issue by balayokesh** [Tejas-Dalvi-99/Help-Me#24]
Hi I would like to add backend to this web application so that when user submits the `Emergency Form.html` the responses will be stored on the database.

**Comment by Tejas-Dalvi-99** [comment]
Sure you can start the working on database, but we will also need to retrieve the data from the database and show in the notifications panel ( the users message ), So that the hospitals will Accept or Reject the Notification.

**Comment by balayokesh** [comment]
> Sure you can start the working on database, but we will also need to retrieve the data from the database and show in the notifications panel ( the users message ), So that the hospitals will Accept or Reject the Notification.

I am not sure about the retrieval part.  I guess we can improve that in another Pull request.  

If its alright please assign this issue to me under hactoberfest label

**Comment by Tejas-Dalvi-99** [comment]
Okay !

**Comment by Tejas-Dalvi-99** [comment]
Hey ! @balayokesh what are updates on the task ?

**Comment by balayokesh** [comment]
> Hey ! @balayokesh what are updates on the task ?

Hi sorrry for delay.  I'll update you within tonight

**Comment by Tejas-Dalvi-99** [comment]
Sure

**Comment by balayokesh** [comment]
I have implemented the functionality.  Just need to make some slight modifications.  I'll make a pull request by tomorrow
