### ISSUE TITLE
Add styling to Emergency form

### ISSUE THREAD

**Issue by MadhuSaini22** [Tejas-Dalvi-99/Help-Me#27]
@Tejas-Dalvi-99 , please assign this task to me, with Hacktoberfest Label

**Comment by Tejas-Dalvi-99** [comment]
You can work on it

**Comment by MadhuSaini22** [comment]
> You can work on it

@Tejas-Dalvi-99 , Made an PR on this issue, Please merge

**Comment by Tejas-Dalvi-99** [comment]
Can you do a Separate PR On the Form Part only, Actually there are some changes in the home screen layout ,

**Comment by MadhuSaini22** [comment]
In the Home page as well, according to your need
Changed this:
![2022-10-10 (1)](https://user-images.githubusercontent.com/81684710/194903067-e11015e5-1405-4092-b3c1-0ca3f6da2d8c.png)
from this:
![2022-10-10 (2)](https://user-images.githubusercontent.com/81684710/194903171-9a2484b3-151b-4b47-954d-c273d986d92d.png)
