### ISSUE TITLE
I would suggest you to host this website through github pages

### ISSUE THREAD

**Issue by akshitagupta15june** [Tejas-Dalvi-99/Help-Me#5]

**Comment by deepeshmlgupta** [comment]
Hi, there please assign me this so that I can host you website on github pages

**Comment by akshitagupta15june** [comment]
I have deployed your site in my local main
So I can see the button help me is not working

**Comment by akshitagupta15june** [comment]
It needs a connectivity to emergency.html
I can work on it

**Comment by Tejas-Dalvi-99** [comment]
> Hi, there please assign me this so that I can host you website on github pages

@deepesh0706 right now we are in developing phase so we'll need some more files to be created and connected with each other, i'll update you once we finish them, then you can work on the hosting process. till then you can work on our other issues. 

Happy Contributing :)

**Comment by Tejas-Dalvi-99** [comment]
you can start the hosting process on github pages

**Comment by akshitagupta15june** [comment]
Thanks

**Comment by akshitagupta15june** [comment]
Hi @Tejas-Dalvi-99 i have hosted it from GitHub pages
at https://akshitagupta15june.github.io/Help-Me/
U can also do the same

I can improve your website UI

**Comment by Tejas-Dalvi-99** [comment]
Hey @akshitagupta15june can you please provide any Youtube link or list down the steps on the Hosting process on Github Pages.

**Comment by akshitagupta15june** [comment]
go to your project settings ->click on pages

![image](https://user-images.githubusercontent.com/57909583/194206827-2f314413-8703-4457-b770-c2b1fac97af3.png)

add your branch as main and click on save

![image](https://user-images.githubusercontent.com/57909583/194207018-969f280e-b275-4114-9f9a-e6f82f718475.png)


your site will be live and hosted -> just click on it 

whatever changes you make on ur repo it will be automatically reflected

![image](https://user-images.githubusercontent.com/57909583/194207224-4df887b1-c718-4be3-bfd6-98c1315c0911.png)

**Comment by akshitagupta15june** [comment]
@Tejas-Dalvi-99

**Comment by Tejas-Dalvi-99** [comment]
Thanks @akshitagupta15june for your valuable information, The Website is Hosted on https://tejas-dalvi-99.github.io/Help-Me/
