### ISSUE TITLE
Add on click to the help me button 

### ISSUE THREAD

**Issue by akshitagupta15june** [Tejas-Dalvi-99/Help-Me#7]
I will be connecting it to emergency form.html

Please assign me

**Comment by Tejas-Dalvi-99** [comment]
By tomorrow our CSS Formatted Homepage will be live, i'll Assign it to you once it goes live. :)

**Comment by akshitagupta15june** [comment]
Thanku

**Comment by akshitagupta15june** [comment]
@Tejas-Dalvi-99 is it live?

**Comment by Tejas-Dalvi-99** [comment]
Yup

**Comment by Tejas-Dalvi-99** [comment]
The Connection of the button has been made, you can work on other issues and improving the U.I of Homepage
